### ISSUE TITLE
检查缺失mod时报错panic: runtime error: index out of range [3] with length 0

### ISSUE THREAD

**Issue by Riachel** [GenesisAN/KKCardModCheck#2]
```
││║[1/82]E:\Koikatu\UserData\chara\female\74442772_p1.png                                                              
║││║[2/82]E:\Koikatu\UserData\chara\female\74579308_p11.png                                                            
 ║││║[4/82]E:\Koikatu\UserData\chara\female\74901327_p7.png                                                              
║││║[5/82]E:\Koikatu\UserData\chara\female\74901327_p8.png                                                             
 ║││║[6/82]E:\Koikatu\UserData\chara\female\76204140_p4.png                                                              
║││║[7/82]E:\Koikatu\UserData\chara\female\77109168_p0.png                                                             
 ║││║[8/82]E:\Koikatu\UserData\chara\female\77131662_p0.png                                                              
║││║[9/82]E:\Koikatu\UserData\chara\female\77162357_p8.png                                                             
 ║││║[10/82]E:\Koikatu\UserData\chara\female\77351239_p4.pngpanic: runtime error: index out of range [3] with length 0   ║│
│║                                                                                                                    
║│
│║                                                                                                                 goroutine 24 [running]:                                                                                                    ║│
│║                encoding/binary.littleEndian.Uint32(...)                                                            
║│
│║                                                              encoding/binary/binary.go:80                         
 ║│
│║                                                                                          KKCardModCheck/card.ParseKoiChara(0xc000f33cf0)                                                                                                   ║│
│║                      KKCardModCheck/card/KoiCard.go:27 +0x10ba                                                     
║│
│║                                                               KKCardModCheck/card.ReadCardKK({0xc0001ef000?, 0xc0001ec000?})                                                                                                               ║│
│║      KKCardModCheck/card/CardRead.go:66 +0x31b                                                                     
║│
│║                                               main.checkAllCardMods.func1.1()                                      
║│
│║                                                                                      KKCardModCheck/main.go:314+0x67d
├created by main.checkAllCardMods.func1
│                   软件为作者免费发布，KKCardModCheck/main.go:311 +0x33c吗....很符合.....后面忘了                    │

E:\Koikatu>pause
Press any key to continue . . .
```

**Comment by Riachel** [comment]
我尝试去移除了这些报错发生时对应的人物卡 于是我每移除一个 这个报错出现的时候就提前一个 而且顺序都一样....

**Comment by Riachel** [comment]
我把我的前11个角色卡移除之后他就直接报错了 啊哈哈哈哈哈
![QQ截图20230128072249](https://user-images.githubusercontent.com/79738368/215224270-19e90856-0169-49c4-8e7a-2ecca20baa85.jpg)

**Comment by GenesisAN** [comment]
报错部分来看，应该是读取卡片数据时出错了，有可能是卡片数据损坏。报错那部分我没对卡片数据长度进行校验如果后面数据缺失，是可能造成该问题。你检查一下，具体哪张卡片导致它崩溃，如果可以的话可以将其打包到zip提交到该问题下。我会细看卡片内部数据。然后尝试增加数据校验步骤，防止这类问题再次发生。

**Comment by GenesisAN** [comment]
试试这个[v0.1.3预览版本](https://github.com/GenesisAN/KKCardModCheck/releases/tag/v0.1.3)是否修复了该问题

**Comment by GenesisAN** [comment]
在v0.1.4版本中年又进行了一个类似问题的修复

[fix: 卡片头内容顺序导致读取错误](https://github.com/GenesisAN/KKCardModCheck/commit/c106eea2048c25cb2779c50ab06cecb5f731eb73)

你可以尝试新的[v0.1.4版本](https://github.com/GenesisAN/KKCardModCheck/releases/tag/v0.1.4)

**Comment by GenesisAN** [comment]
如果问题依旧存在，请开一个新的issues回复我
